suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(parallel))
suppressPackageStartupMessages(library(GenomicRanges))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(vroom))
suppressPackageStartupMessages(library(pryr))
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
options(stringsAsFactors = FALSE)
# options(scipen = 999)
mc <- getOption('mc.cores', 36)
getwd()

mat = as.matrix(fread("ZNF93.meme.mat", header = FALSE, col.names = c("A", "C", "G", "T")))
mat_t = t(mat)
mat_t

library(ggseqlogo)
library(ggplot2)
pdf("ZNF93.meme.pdf", width = 5, height = 3)
ggseqlogo(mat_t)
dev.off()
